### ISSUE TITLE
Chokidar does not seem to trigger when running in Kubernetes utilizing Azure blob storage as a volume mount

### ISSUE THREAD

**Issue by ainsey11** [paulmillr/chokidar#1203]
**Describe the bug**

When running chokidar inside a container, running inside Kubernetes utilising a volume mount from Azure files, chokidar does not trigger when a new file is placed in the directory.

**Versions (please complete the following information):**
 - Chokidar version 3.5.3
 - Node version 14
 - OS version: node:14-buster-slim

**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.

Create a volume claim in kubernetes using the azure files driver (https://docs.microsoft.com/en-us/azure/aks/azure-files-csi) 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filedrop
  namespace: test
spec:
  storageClassName: azurefile-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
```

Mount that inside your container:
```
      volumes:
        - name: filedrop-storage
          persistentVolumeClaim:
            claimName: filedrop
```

launch the container - then see the mount (info redacted for security reasons) :
```
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)
//fe646d3XXXXXXXXXX.file.core.windows.net/pvc-aaafe646d3XXXXXXXXXX on /filedrop type cifs (rw,relatime,vers=3.1.1,cache=strict,username=XXXXXXXXX,uid=0,forceuid,gid=0,forcegid,addr=XXXXXXX,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,mfsymlinks,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=30)
/dev/sda1 on /etc/hosts type ext4 (rw,relatime,discard)
/dev/sda1 on /dev/termination-log type ext4 (rw,relatime,discard)
/dev/sda1 on /etc/hostname type ext4 (rw,relatime,discard)
/dev/sda1 on /etc/resolv.conf type ext4 (rw,relatime,discard)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```
observe files placed inside folder:
```
root@importer-8477XXXXXXXpc ls /filedrop/pdf/ -l
total 2870
-rwxrwxrwx 1 root root 2180481 Feb  3 22:10 Test.pdf
```

Chokidar does not trigger an event

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
let w = Chockidar.watch(
            wp.calculatedPath,
            {
                ignored: /(^|[\/\\])\../, // ignore dotfiles
                usePolling:true,
                depth: 1,
                interval: 1000,
                awaitWriteFinish: {
                    stabilityThreshold: 30000,
                    pollInterval: 500
                }
            });
        w.on('add', (file,stats) => this.fileTrigger(file,stats,wp));
```

Most valuable could be one or more test cases for [test.js](https://github.com/paulmillr/chokidar/blob/master/test.js) to demonstrate the problem.

**Expected behavior**
the add event to trigger

**Additional context**
trying to use Azure Files as a file repository to then trigger a service which imports the files into an application. Files are uploaded into Azure over SFTP and then chokidar is to trigger when they have uploaded and begin the import process
